In [27]:
import qnetvo as qnet
from context import utilities

import pennylane as qml

import matplotlib.pyplot as plt
from pennylane import numpy as np
import re
from qiskit import IBMQ


In [28]:
provider = IBMQ.load_account()


In [33]:
dev = qml.device("default.qubit", wires=[0,1])

ibm_dev = qml.device("qiskit.ibmq",
    wires=[0,1],
    shots= 6000,
    backend ="ibmq_qasm_simulator",
    provider=provider
)

@qml.qnode(ibm_dev, diff_method="param-shift")
def test_qnode(settings):
    qml.ArbitraryStatePreparation(settings, wires=[0,1])
    
    return qml.expval(qml.PauliZ(wires=[0]) @ qml.PauliZ(wires=[1]))



QuantumFunctionError: Differentiation method param-shift not recognized. Allowed options are ('best', 'parameter-shift', 'backprop', 'finite-diff', 'device', 'reversible', 'adjoint').

In [30]:
print(qml.draw(test_qnode)([0,0,0,0,0,0]))

 0: ──╭RX(0)──╭RY(0)──╭RI(0)──╭RI(0)──╭RX(0)──╭RX(0)──╭┤ ⟨Z ⊗ Z⟩ 
 1: ──╰RI(0)──╰RI(0)──╰RX(0)──╰RY(0)──╰RX(0)──╰RY(0)──╰┤ ⟨Z ⊗ Z⟩ 



In [31]:
def cost(settings):
    return -(test_qnode(settings))



In [32]:
qnet.gradient_descent(
    cost,
    np.random.rand(6),
    sample_width = 5,
    num_steps = 20,
    step_size=0.2
)

iteration :  0 , score :  0.49466666666666664
elapsed time :  203.08574676513672
iteration :  5 , score :  0.885
elapsed time :  241.87627506256104
iteration :  10 , score :  0.9846666666666667
elapsed time :  46.42234706878662
iteration :  15 , score :  0.9983333333333333
elapsed time :  77.8572289943695


{'datetime': '2022-01-20T20:56:54Z',
 'opt_score': tensor(0.99966667, requires_grad=True),
 'opt_settings': tensor([0.00869472, 0.00866354, 0.01555085, 0.00277175, 0.67063925,
         0.85816271], requires_grad=True),
 'scores': [tensor(0.49466667, requires_grad=True),
  tensor(0.885, requires_grad=True),
  tensor(0.98466667, requires_grad=True),
  tensor(0.99833333, requires_grad=True),
  tensor(0.99966667, requires_grad=True)],
 'samples': [0, 5, 10, 15, 20],
 'settings_history': [tensor([0.54622806, 0.37969688, 0.87355085, 0.17370509, 0.67123925,
          0.85406271], requires_grad=True),
  tensor([0.48386139, 0.34029688, 0.75408419, 0.15390509, 0.67100591,
          0.85419605], requires_grad=True),
  tensor([0.42179472, 0.29909688, 0.64591752, 0.13660509, 0.67170591,
          0.85646271], requires_grad=True),
  tensor([0.36169472, 0.25509688, 0.54098419, 0.11877175, 0.67227258,
          0.85722938], requires_grad=True),
  tensor([0.30056139, 0.21113021, 0.44808419, 0.10070509,